meta_product_name: Mes outils partagés

meta_title: Mes outils partagés - outils en ligne

meta_description: Nos 5 outils vous permettent de gérer vos finances, de vérifier l'orthographe d'un mot, d'obtenir par mail les news de journaux, de consulter les prévisions météos par ville et de raccourcir des urls longues.

meta_image: social_img.png # should exist in `app/assets/images/`
