meta_product_name: Mes outils partagés

meta_title: Mes outils partagés - outils en ligne

meta_description: Nos 3 outils vous permettent d'obtenir par mail les news de journaux, de consulter les prévisions météos par ville, de raccourcir des urls longues.

meta_image: social_img.png # should exist in `app/assets/images/`
