# config/sidekiq.yml
:concurrency: 3
:timeout: 60
:verbose: true
:queues:
  # Queue priority:
  # https://github.com/mperham/sidekiq/wiki/Advanced-Options
  # https://mikerogers.io/2019/06/06/rails-6-sidekiq-queues
  - default

:scheduler:
  :schedule:
    send_mail:
      cron: '10 9 * * *'   # Runs every day at 9h10 am
      class: SendMail
    every_month_job:
      cron: '0 2 * * *'    # Runs every day at 2h am
      class: EveryMonthJob
    every_year_job:
      cron: '05 2 * * *'    # Runs every day at 2h05 am
      class: EveryYearJob
    every_day_job:
      cron: '10 2 * * *'    # Runs every day at 2h10 am
      class: EveryDayJob
    every_week_job:
      cron: '15 2 * * *'    # Runs every day at 2h15 am
      class: EveryWeekJob
