# config/sidekiq.yml
:concurrency: 3
:timeout: 60
:verbose: true
:queues:
  # Queue priority:
  # https://github.com/mperham/sidekiq/wiki/Advanced-Options
  # https://mikerogers.io/2019/06/06/rails-6-sidekiq-queues
  - default

:scheduler:
  :schedule:
    send_mail:
      cron: '10 9 * * *'   # Runs every day at 9h10 am
      class: SendMail
    every_month_job:
      cron: '0 1 * * *'    # Runs every day at 1h am
      class: EveryMonthJob
    every_year_job:
      cron: '0 2 * * *'    # Runs every day at 2h am
      class: EveryYearJob
    every_day_job:
      cron: '0 3 * * *'    # Runs every day at 3h am
      class: EveryDayJob
    every_week_job:
      cron: '0 4 * * *'    # Runs every day at 4h am
      class: EveryWeekJob
